### ISSUE TITLE
Debugger widget enables itself on each load

### ISSUE THREAD

**Issue by Beee4life** [mac-cain13/xdebug-helper-for-chrome#109]
As the subject says, on every page load, the debugger is active, even though I disable it.

I don't know how it's triggered (automatically). Afaik I didn't...

Anyone have any suggestions on how to fix it?

**Comment by bilogic** [comment]
I face the exact opposite.

1. Enabled the debugger
2. Reload the page
3. Debugger becomes disabled...

**Comment by pogla** [comment]
> I face the exact opposite.

Same here. @bilogic Did you find any solutions?

**Comment by pogla** [comment]
I removed the plugin and installed it again and it seems to be working now.

**Comment by bilogic** [comment]
@pogla I switched to https://chrome.google.com/webstore/detail/xdebug-chrome-extension/oiofkammbajfehgpleginfomeppgnglk

**Comment by brajno** [comment]
@bilogic Clearing cookies did it for me

**Comment by Beee4life** [comment]
I am closing this, because not really using it anymore...
