### ISSUE TITLE
Add a keyboard shortcut to enable/disable xdebug helper

### ISSUE THREAD

**Issue by gdance** [mac-cain13/xdebug-helper-for-chrome#13]
Hello,

I think it would be great if you could set a keyboard shortcut in Preferences > Extensions-> Configure Commands that allowed you to enable/disable xdebug helper.

It is discussed here:

http://developer.chrome.com/trunk/apps/commands.html

Thanks for the great extension!!

**Comment by Natesuri** [comment]
Could we make this optional or customizable? It's clashing with some other fixed keyboard shortcuts.

**Comment by mkopinsky** [comment]
@Natesuri you can configure it by going to chrome://extensions/shortcuts (or opening extensions, opening the hamburger menu, and clicking Keyboard Shortcuts)
