### ISSUE TITLE
Debug only ajax requests (xhr)

### ISSUE THREAD

**Issue by kirugan** [mac-cain13/xdebug-helper-for-chrome#39]
What a nice feature would be if we can debug only xhr requests. 
Currently i have a web project where a lot of elements start loading after layout loaded.
How i debug it now:

1) Set breakpoint or 'debugger;' statement inside code
2) Waiting when xhr breakpoint start debugger
3) Turn on debug mode in xdebug helper
4) Debug in my IDE

By the way breakpoint must be set before xhr actually send data!

This feature can be implemented with prototype property of xhr (setting callback before xhr starts)

**Comment by mac-cain13** [comment]
Like this idea, but don't have the time/need to implement this myself. So feel free to implement this and submit a PR, will be happy to merge that in!
