### ISSUE TITLE
Helper switches to disabled when a request returns xml

### ISSUE THREAD

**Issue by frankmayer** [mac-cain13/xdebug-helper-for-chrome#42]
If there is a call to a script which returns an xml structure, the helper gets disabled upon the response and cannot be enabled again.
If then calling another script in the same tab, which produces non-xml output, the helper gets enabled again.

**Comment by mac-cain13** [comment]
Correct, it sets a cookie on the domain. So you enable/disable it for all calls on a specific domain. If there are any bugs with this or with XML output, please provide some steps how I can reproduce the issue or even better; submit a pull request. :)
