### ISSUE TITLE
Configure xdebug.profiler_enable_trigger_value

### ISSUE THREAD

**Issue by 2ge** [mac-cain13/xdebug-helper-for-chrome#49]
According http://xdebug.org/docs/profiler in xdebug version 2.3 was added xdebug.profiler_enable_trigger_value

it would be nice to set this value in options of this great plugin

**Comment by mac-cain13** [comment]
Good suggestion! I'll see if I have time to implement this.

If someone wants to implement this and send a PR please let me know!

**Comment by mac-cain13** [comment]
Thanks to https://github.com/mac-cain13/xdebug-helper-for-chrome/pull/57 this is available in the latest release!
