### ISSUE TITLE
How to use the application?

### ISSUE THREAD

**Issue by johnbendi** [mac-cain13/xdebug-helper-for-chrome#51]
Is it not proper that there should be an instruction about how to use this extension?

**Comment by vreemt** [comment]
The extension page (see link at the top of the repository), repository readme and the options page chrome-extension://eadndfjplgieldjbigjakmdgkmoaaaoc/options.html (or use Google Chrome > Settings > Extensions > Xdebug helper) include instructions. To configure your IDE to use Xdebug is a separate issue and linked to in the extension settings (link at the top). 

To use Xdebug with PHPStorm when you're running vagrant (like me), see the article https://danemacmillan.com/how-to-configure-xdebug-in-phpstorm-through-vagrant/

**Comment by mac-cain13** [comment]
Thanks @vreemt.

Agree we could elaborate more about how to use Xdebug. On the other hand, this tool targets users of Xdebug that now how it works and then want to make their life easier.

Anyway, a PR with instructions is very welcome.
