### ISSUE TITLE
Idea to easily enable/disable debugging

### ISSUE THREAD

**Issue by rishadomar** [mac-cain13/xdebug-helper-for-chrome#54]
Most of the time I'm enabling/disabling the debugger and not switching on/off profiling and trace.
So would be real handy to have a hotkey to just enable debugger. Like ctrl-shift-d

**Comment by mac-cain13** [comment]
Agreed! Would be nice!

Shouldn't be too hard to build in. I don't have time to build this in myself anytime soon, so please feel free to develop this feature and send a PR!

**Comment by mac-cain13** [comment]
This is possible you can set the shortcut on the extensions settings page. It will toggle between the debug and disabled state.
