### ISSUE TITLE
On a host that has a redirect loop you are unable to select options in the popup

### ISSUE THREAD

**Issue by incon** [mac-cain13/xdebug-helper-for-chrome#56]
On a host that has a redirect loop you are unable to select options in the popup

extensions::uncaught_exception_handler:8 Error in response to runtime.getBackgroundPage: TypeError: Cannot read property 'status' of undefined
at chrome-extension://eadndfjplgieldjbigjakmdgkmoaaaoc/popup.js:45:41
at chrome-extension://eadndfjplgieldjbigjakmdgkmoaaaoc/popup.js:44:21

**Comment by mac-cain13** [comment]
Thanks for reporting this. Strange that the response is not working correctly!

Currently I've no time to fix this, but please feel free to submit a PR with a fix.

**Comment by incon** [comment]
Never played with chrome extensions, but it appears content scripts cannot be loaded on error pages.

**Comment by mac-cain13** [comment]
Sounds plausible, then I think we can't really fix it, right?

**Comment by mac-cain13** [comment]
Seems like we can't do anything as an extension on errorpages.
