### ISSUE TITLE
Support a session tokens per domain

### ISSUE THREAD

**Issue by Michal-sk** [mac-cain13/xdebug-helper-for-chrome#58]
Sometimes when working with multiple projects, i would like to have a different session id set.

So i would like to suggest:
- Change the debug chrome menu, change entry debug to 'debug with default session' (will use the session from the plugin settings. And add entry under that with 'debug with session' (will popup and show a list of session ids used previously and a text box to enter manually a new session id?)

We can not listen to different hosts with the same session id in PHP storm and i gues in other IDEs neither.

**Comment by mac-cain13** [comment]
Interesting suggestion. It feels a bit complicated, but I can see it could be handy in some situations. I don't have time to implement this now, but I'm open to a pull request that implements this in a nice way.
