### ISSUE TITLE
Xdebug helper icon disappeared from Chrome address bar

### ISSUE THREAD

**Issue by binary-data** [mac-cain13/xdebug-helper-for-chrome#60]
Today my Chrome (on Linux) was updated to verson 49.0.2623.75 and extension icon disappeared from address bar (though I still able to control xdebug through extension icon that located in standart extension icons bar)

**Comment by maxxscho** [comment]
+1 Same here on OS X

**Comment by JosephLeedy** [comment]
Mine seems to have migrated to the toolbar, along with another extension that has been in the address bar for years.

**Comment by ElijahLynn** [comment]
Truth, same here. Ubuntu 14.04 + Chrome 48.0.2564.97

**Comment by mac-cain13** [comment]
Yeah, not much to do about that. It's how Chrome works since version 48. See also these links:

- https://productforums.google.com/d/msg/chrome/6X_W3yT6__U/EHkez4j-CAAJ
- https://bugs.chromium.org/p/chromium/issues/detail?id=397259#c18

Seems Google thinks it's better to have them in the toolbar instead of the addressbar.

**Comment by ElijahLynn** [comment]
Fair enough.

**Comment by benyaminshoham** [comment]
I also see the icon in the toolbar and not in the address bar. However, on the toolbar the icon doesn't have the option to enable/disable debugging, and now I can't debug locally. Any advice?

**Comment by binary-data** [comment]
@benyaminshoham These options available on a simple left-click on a toolbar icon
![xdebug](https://cloud.githubusercontent.com/assets/875296/14074050/1e74765e-f4df-11e5-8324-77e46f283b08.jpg)

**Comment by benyaminshoham** [comment]
Not for me :(
![screen shot 2016-03-28 at 11 26 22 am](https://cloud.githubusercontent.com/assets/1109760/14074210/00297548-f4d8-11e5-820e-3263d3737269.png)

**Comment by benyaminshoham** [comment]
Actually, many people complain that since last Chrome update (V 49) the debug icon is missing for them.

https://chrome.google.com/webstore/detail/xdebug-helper/eadndfjplgieldjbigjakmdgkmoaaaoc/support

**Comment by binary-data** [comment]
@benyaminshoham Is there a way to do something like "right click" on a Mac? And then see what will happen with icon

I personally don't familiar with Mac, so unfortunately can't help you there :(

**Comment by benyaminshoham** [comment]
Right-click doesn't work as well.
I abandoned this extension for now, and managed to set up a permanent connection between my browser and IDE by setting up xdebug properly in the php.ini. Attached are the ini declarations.

<pre>
[xdebug]
zend_extension="/usr/local/Cellar/php56-xdebug/2.2.6/xdebug.so"
xdebug.remote_enable=on
xdebug.default_enable=on
xdebug.remote_autostart=off
xdebug.remote_port=9000
xdebug.remote_host=localhost
xdebug.profiler_enable_trigger=1
xdebug.profiler_output_name=xdebug-profile-cachegrind.out-%H-%R
xdebug.var_display_max_children = 128
xdebug.var_display_max_data = 2048
xdebug.var_display_max_depth = 128
​
xdebug.remote_autostart = 1
xdebug.remote_enable=1
;xdebug.profiler_enable=1
;xdebug.profiler_output_dir="/tmp/xdebug"
</pre>

also, in the IDE (Mine is phpStorm) you have to set up xdebug to listen on the same port number (9000 in my case)

**Comment by binary-data** [comment]
If you use PHPStorm, you have two options: set [bookmarklets](https://www.jetbrains.com/phpstorm/marklets/) for browser or use "Start/Stop listening for PHP debug conections" button.
But IMHO using Xdebug helper is more comfortable

**Comment by mac-cain13** [comment]
@benyaminshoham Are you using an alias for localhost or something like that? If so, maybe you run into this: https://github.com/mac-cain13/xdebug-helper-for-chrome/issues/64#issuecomment-199778603?

**Comment by mac-cain13** [comment]
Just released version 1.5, that should always show the debug menu. Hope that helps preventing issues like this.

**Comment by salimibrohimi** [comment]
The xdebug helper menu is not visible - can't enable it. Can't debug.
Arch Linux, Google Chrome Version 94.0.4606.54 (Official Build) (64-bit).
