### ISSUE TITLE
Can't access main debug menu

### ISSUE THREAD

**Issue by JamesStidard** [mac-cain13/xdebug-helper-for-chrome#64]
Since Chrome updated and moved the extension from the address bar, I can no longer click it to reveal the menu where you can toggle the debugging broadcaster.

I only receive the right-click menu (even when I just left click) and the keyboard shortcuts also do not work for me.

I'm not seeing any errors in the developer console and I've tried uninstalling and reinstalling.

Here's a screenshot of the menu I do see when I left of right click the bug.

<img width="215" alt="screen shot 2016-03-21 at 12 29 50 pm" src="https://cloud.githubusercontent.com/assets/1797906/13918828/918db3cc-ef61-11e5-8664-ff7eec1b501b.png">

Let me know if there is anything I can do to help debug the problem.

**Comment by stwalkerster** [comment]
I'm suffering what I believe to be the same issue, however I have noticed that I only have issues when attempting to enable debugging from localhost.

**Comment by JamesStidard** [comment]
That would align with me. I only debug projects on localhost.

**Comment by JamesStidard** [comment]
Okay, I managed to get the debugger options to reappear for me. I have a feeling that Chrome have changed the URL they send to the extension.

My development environment routes *.dev domains to my localhost so I use myproject.dev instead of localhost:8080/myproject. So in the options for the extension I had the domain filter for .dev and this use to work fine. I never use localhost:8080/* so I never added it to the filter.

It appears that the extension is now seeing the domain as localhost instead, even though the url shows *.dev. I added localhost to the domain filter and it now works. Interestingly not specifying localhost at all seems to also mean I can't see the options menu.

@stwalkerster Does it also solve your problem to add 'localhost' to the domain filter?

**Comment by mac-cain13** [comment]
Since Google turned over extensions it looks like filters are not really helping anymore. It'll only make things more confusing. I think the domain filter should be removed in a future version.

**Comment by mac-cain13** [comment]
Version 1.5 is just released, this converts the extension to a browser extension, making the menu always visible and fixes some other issues. Hope this will help everybody out!

**Comment by klaernie** [comment]
@mac-cain13 I wish you had pointed out this issue more prominently. I was expecting to have it show up on my dev-domains, but wondering why it wasn't there. Just to find out, that domain-specific visibility is gone. Headed to the issues page, to maybe open an issue about this possible regression, doing my research and finding out, that the latest release was built that way by design. Well, 20min down the drain, now back to what I originally wanted.

**Comment by mac-cain13** [comment]
I'm very sorry about the 20 minutes you lost @klaernie, but I don't get the problem you're describing, you say:
> I was expecting to have it show up on my dev-domains, but wondering why it wasn't there.

Then you point out that the domain filter is gone so you have the menu available on every website by design now. (Also on your dev domains.) So no problem there right?

**Comment by klaernie** [comment]
well, the menu's position moved - I was expecting it in the addressbar, but the chrome change moved it next to the bunch of extensions, that I don't need as often. And it's hard to spot the difference when extensions are added, that makes it hard to spot between chrome restarts. Also I was gone from developing for a couple weeks, and didn't miss the pageaction button, as it was only supposed to show on my dev domains.

No hurt feelings on my side, I am very thankful for your commitment and time. The only thing I wished you did is announcing it better.

**Comment by mac-cain13** [comment]
Yeah, that's correct, Google moved the position of all address bar extensions. I don't think it is an improvement, but it is something we have to live with. It moved to there without updating the extension, it's purely a Chrome update in which they moved all the icons over. I only made changes to adapt to that.

I understand why it is confusing and you should bring that up to the Google Chrome development team.

**Comment by JamesStidard** [comment]
Hi @mac-cain13 , Thanks for the quick response to this ticket and for your work in general.
