### ISSUE TITLE
Feature Request : Turn XDebug On or Off in  php.ini

### ISSUE THREAD

**Issue by sadortun** [mac-cain13/xdebug-helper-for-chrome#67]
Hi!

Since XDebug have a huge impact on page performance, it would be nice to have a callback to turn it on or off by changing the `php.ini` file when enabling or disabling it in the browser.

I am not quite sure how it can be done, but if you give me some guidelines, i would be very happy to submit a PR

Thanks!

**Comment by neochief** [comment]
I don't think it's possible, since browser extension does not have access to file system.

**Comment by sadortun** [comment]
Is there a way for an external tool to query the extension status ?

**Comment by kirugan** [comment]
@sadortun well it`s kinda possible, but it`ll be awkward solution.

**Comment by mac-cain13** [comment]
As @neochief states, this will be very hard to build.
