### ISSUE TITLE
Extension not working for certain sites

### ISSUE THREAD

**Issue by reypm** [mac-cain13/xdebug-helper-for-chrome#68]
@mac-cain13 I have the latest version of the extension installed on Chrome Version 52.0.2743.49 beta-m (64-bit) and for some reason I can't enable/disable. It work at some point but lately I can't get it to work and I can't find why, could you help me? Did you need something from me? (as for example a log file or some debug stuff?)

**Comment by mac-cain13** [comment]
Seems to work for me on the Stable version of Chrome (version 51). So I'm not yet sure if they broke something in the beta or it's really because of an API change.

Could you also give it a try in the stable Chrome? Is that working for you?

**Comment by reypm** [comment]
@mac-cain13 Nope, isn't working. I have tried on Version 51.0.2704.106 m (64-bit) could be any problem with 64 bits version? I haven't deleted the previous config from Chrome Beta could that be an issue? I mean how do I make a clean install of the extension?

**Comment by reypm** [comment]
@mac-cain13 I have tried even setup values manually and still not working, take a look to the following pictures:

**Local Storage**
![2016-07-02_10-26-04](https://cloud.githubusercontent.com/assets/627886/16540819/92fc8e48-403f-11e6-9c04-e357277a9cc0.png)

**Session Storage**
![2016-07-02_10-26-19](https://cloud.githubusercontent.com/assets/627886/16540821/92fef3a4-403f-11e6-9062-d5faa67c75b6.png)

**Cookies**
![2016-07-02_10-26-33](https://cloud.githubusercontent.com/assets/627886/16540820/92fcf554-403f-11e6-8a62-c7042799dba1.png)

What else I need to get this working properly? Any suggestion from you?

BTW, I am using Windows 10 x64 if this helps

**Comment by reypm** [comment]
@mac-cain13 nvm, now is working and I don't know how or why, I just made those changes showed above and start working but the bug icon still in gray not in green :) that's it

**Comment by mac-cain13** [comment]
Great to hear it's fixed. :)
