### ISSUE TITLE
deactivate or change the shortcut

### ISSUE THREAD

**Issue by davdenic** [mac-cain13/xdebug-helper-for-chrome#71]
Hi, i'd like to change the shortcut or deactivate it.
Thanks you

**Comment by mac-cain13** [comment]
You can do this in Chrome Settings, Extension page, bottom right there is a shortcuts link. If you click that you can change shortcuts per extension.

**Comment by pr3mar** [comment]
I think you cannot do this any more in newer version of chrome, can you please add it?
