### ISSUE TITLE
Key shortcut doesn't work

### ISSUE THREAD

**Issue by antonmarin** [mac-cain13/xdebug-helper-for-chrome#76]
no reaction when press ctrl+shift+x.
Ubuntu 16.04, Chrome 53. Bug exists at least in Chrome 51

**Comment by mac-cain13** [comment]
Seems to work on my machine. If you look in `Settings -> Extensions -> Shortcuts` (bottom right on the page) do you see the shortcut set?

**Comment by antonmarin** [comment]
Settings of what? System, chrome or extension?

**Comment by mac-cain13** [comment]
Chrome.

chrome://extensions/ -> Bottom right

**Comment by antonmarin** [comment]
Was Alt+Shift+X. Strange thing. Changed to ctrl+shift+X and it works again
