### ISSUE TITLE
Activate by Tab (not Domain)

### ISSUE THREAD

**Issue by akazik** [mac-cain13/xdebug-helper-for-chrome#77]
I'd really prefer it if the xdebug option can be switched on/off per browser tab and not per domain.

My scenario: I want only to debug the frontend, not the backend of a site. Need the backend to change parameters to test them on the frontend. Both are running on the same domain.
Or: I have a site which runs on several domains and I want to debug even if redirected to another domain.

I really like the helper, and I think that would be more intuitive.

**Comment by mac-cain13** [comment]
The helper is currently implemented by setting a cookie, this triggers Xdebug. I think it isn't possible to just set a cookie for a specific tab.

Do you have any ideas how this technically should be implemented?

**Comment by akazik** [comment]
Sorry, I have no idea how to implement it. Just thought it could be a nice idea.

**Comment by mac-cain13** [comment]
I might have reacted a bit quickly and too the point this morning, I'm sorry. 

Your very welcome to share your idea, it would be a nice thing to create if it was possible to do so! Thanks for using the extension and sharing your suggestion. :)

**Comment by ilyar** [comment]
@mac-cain13 idea: use trigger Xdebug on blank page as global default state.
