### ISSUE TITLE
Cmd-Shift-X

### ISSUE THREAD

**Issue by SeanKnight** [mac-cain13/xdebug-helper-for-chrome#80]
Google Docs now uses Cmd-Shift-X for strikethrough. It would be nice to have a checkbox in options menu to disable the keyboard shortcut.

**Comment by mac-cain13** [comment]
Thanks for letting me know. Note that you can configure/customize shortcuts for Chrome extensions on the bottom right of the chrome://extensions/ page. :)

**Comment by erikhansen** [comment]
In case anyone else came across this Github issue like I did, here is how you can edit the hotkey:

![17-21-21 extensions-urnes](https://user-images.githubusercontent.com/129031/32079848-2716ada4-ba72-11e7-9385-3b8bd2c8de51.png)

**Comment by jb510** [comment]
@mac-cain13 thanks, that does work! I wish I'd found and/or known about that option sooner... this has been driving me crazy for months and the only solution I knew of was to enable/disable the extension.

I thought of an alternative solution maybe worht considering.  What about adding the ability to exclude Xedebug helper from running on certain domains/url?  

I, and I assume most, are unlikely to ever want it running anywhere except on a local install (domain.test, domain.local, etc..). I'm sure some use remote dev servers where they'd run it but it's still a limited set. Anyway, just a thought.

I've disabled keyboard shortcuts for Xdebug helper, which is fine, I personally prefer toggling via the icon anyway.

**Comment by zainengineer** [comment]
It is not showing that option to me 😞  (tried developer mode too looks same)
![image](https://user-images.githubusercontent.com/4746235/54795094-f32f0700-4c9e-11e9-8fa3-04e1f42a3085.png)

what can I do to display it ?

**Comment by jb510** [comment]
@zainengineer Thing move...   
Click "Details" on Xedbug, then find and click "options" and there you will find keyboard shortcuts.

**Comment by zainengineer** [comment]
@jb510 detail page has no option to modify keyboard shortcut.
It just displays current keyboard shortcut

![image](https://user-images.githubusercontent.com/4746235/56945472-a6c2cb00-6b6a-11e9-81f5-8913d17b88ab.png)

**Comment by jb510** [comment]
@zainengineer Chrome probably changed the UI again.
