### ISSUE TITLE
I ported this addon for Firefox

### ISSUE THREAD

**Issue by BrianGilbert** [mac-cain13/xdebug-helper-for-chrome#83]
@mac-cain13 
Thanks for making the Chrome plugin, I ported it to Firefox!
https://github.com/BrianGilbert/xdebug-helper-for-firefox

**Comment by mac-cain13** [comment]
Quite cool! Thanks for letting me know, happy to see you've taken the time to make a lot of Firefox users happy with this. :)

I'll add a small reference to your version of the helper in our readme!
